specVersion: 1.0.0
name: subql-demo
version: 0.0.1
runner:
  node:
    name: "@subql/node-cosmos"
    version: "*"
  query:
    name: "@subql/query"
    version: "*"
description: >-
  This project can be use as a starting point for developing your
  Cosmos (Osmosis) based SubQuery project
repository: "https://github.com/subquery/cosmos-subql-starter"
schema:
  file: ./schema.graphql
network:
  chainId: osmosis-1
  # This endpoint must be a public non-pruned archive node.
  # This is a public node that is rate limited, which will affect indexing speed.
  # When developing your project we strongly suggest getting a private API key.
  # endpoint: "https://osmosis.api.onfinality.io/rpc?apikey=b1ffe5e7-3048-4b03-9365-09ad9503ed9c"
  endpoint: "https://osmosis-mainnet-archive.allthatnode.com:26657"
  dictionary: "https://api.subquery.network/sq/subquery/cosmos-osmosis-dictionary"
  chainTypes:
    cosmos.slashing.v1beta1:
      file: "./proto/cosmos/slashing/v1beta1/tx.proto"
      messages:
        - "MsgUnjail"
    cosmos.gov.v1beta1:
      file: "./proto/cosmos/gov/v1beta1/tx.proto"
      messages:
        - "MsgVoteWeighted"
    cosmos.gov.v1beta1.gov:
      # Key is not used, it matches the one above and is inferred from the file
      file: "./proto/cosmos/gov/v1beta1/gov.proto"
      messages:
        - "WeightedVoteOption"
    cosmos.base.v1beta1:
      # needed by MsgCreateVestingAccount
      file: "./proto/cosmos/cosmos.base.v1beta1.coin.proto"
      messages:
        - "Coin"
    osmosis.gamm.v1beta1:
      file: "./proto/cosmos/osmosis/gamm/v1beta1/tx.proto"
      messages:
        - MsgJoinPool
        - MsgSwapExactAmountIn
dataSources:
  - kind: cosmos/Runtime
    startBlock: 1
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleTransaction
          kind: cosmos/TransactionHandler
